app/urls.py
from django.conf.urls import url
 
from app import views
 
urlpatterns = [
    # Examples:
    # url(r'^$', 'bbs_project.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
 
    url(r'^$', views.index),
    url(r'^detail/(\d+)/$', views.bbs_detail),
    url(r'^sub_comment/$', views.sub_comment),
    url(r'^bbs_pub/$', views.bbs_pub),
    url(r'^bbs_sub/$', views.bbs_sub),
    url(r'^category/(\d+)', views.category),
]

bbs/urls.py
# coding=utf-8
from django.conf.urls import include,url
from django.contrib import admin
from app import views
from app import urls
from django.contrib.auth.views import login
import app
 
urlpatterns = [
    # Examples:
    # url(r'^$', 'bbs_project.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
 
    # 配置url
    url(r'^admin/', admin.site.urls),
 
    # 登陆页面url
    url(r'^login/$', login, name='login'),
    url(r'^login/$', views.Login ),
    url(r'^acc_login/$', views.acc_login),
    url(r'^logout/$', views.logout_view),
    url(r'^account/',include('account.urls')),    
    url(r'', include(app.urls)),
    url(r'^blog/', include('blog.urls',
        namespace='blog',
        app_name='blog')),
    url(r'^travel/', include('travel.urls',
        namespace='travel',
        app_name='travel')),
    url(r'^unuse/', include('unuse.urls',
        namespace='unuse',
        app_name='unuse')),
    url(r'^study/', include('study.urls',
        namespace='study',
        app_name='study')),
    url(r'^job/', include('job.urls',
        namespace='job',
        app_name='job')),
]

blog/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from . import views
urlpatterns = [
    # post views
    url(r'^$', views.post_list, name='post_list'),
    # url(r'^$', views.PostListView.as_view(),name='post_list'),
    url(r'^tag/(?P<tag_slug>[-\w]+)/$',views.post_list,
    name='post_list_by_tag'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/'\
        r'(?P<post>[-\w]+)/$',
        views.post_detail,
        name='post_detail'),
    url(r'^bbs_pub$',views.contact),
]

travel/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from . import views
urlpatterns = [
    # post views
    url(r'^$', views.travel_list, name='travel_list'),
    # url(r'^$', views.PostListView.as_view(),name='post_list'),
    url(r'^tag/(?P<tag_slug>[-\w]+)/$',views.travel_list,
    name='travel_list_by_tag'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/'\
        r'(?P<post>[-\w]+)/$',
        views.travel_detail,
        name='travel_detail'),
    url(r'^bbs_pub$',views.contact),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from taggit.managers import TaggableManager

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager,
                    self).get_queryset().filter(status='published')

# Create your models here.
class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    #标题
    title = models.CharField(max_length=250)
    #短标签，为帖子构建URLs
    slug = models.SlugField(max_length=250,
                            unique_for_date='publish')
    #作者
    author = models.ForeignKey(User,
                                related_name='blog_posts')
    #主体
    body = models.TextField()
    #发布时间
    publish = models.DateTimeField(default=timezone.now)
    #创建时间
    created = models.DateTimeField(auto_now_add=True)
    #更新时间
    updated = models.DateTimeField(auto_now=True)
    #帖子展示状态
    status = models.CharField(max_length=10,
                                choices=STATUS_CHOICES,
                                default='draft')
    tags = TaggableManager()

    #在模型（model）中的类Meta包含元数据。我们告诉Django查询数据库的时候
    #默认返回的是根据publish字段进行降序排列过的结果。我们使用负号来指定
    #进行降序排列。
    
    class Meta:
           ordering = ('-publish',)
    #*str()*方法是当前对象默认的可读表现。
    #Django将会在很多地方用到它例如管理站点中。
    def __str__(self):
        return self.title
    
    objects = models.Manager() # The default manager.
    published = PublishedManager() # Our custom manager.
    
    def get_absolute_url(self):
        return reverse('blog:post_detail',
                        args=[self.publish.year,
                              self.publish.strftime('%m'),
                              self.publish.strftime('%d'),
                              self.slug])
    #请注意，我们通过使用strftime()方法来保证个位数的月份和日期
    #需要带上0来构建URL*。我们将会在我们的模板（templates）中使
    #用get_absolute_url()*方法。
    

class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    class Meta:
        ordering = ('created',)
    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.post)

blog/forms.py
# -*- coding: utf-8 -*-
from django import forms

from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'body')

travel/forms.py
# -*- coding: utf-8 -*-
from django import forms

from .models import travelComment

class CommentForm(forms.ModelForm):
    class Meta:
        model = travelComment
        fields = ('name', 'body')

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from .models import Post, Comment
from .forms import CommentForm
from taggit.models import Tag
from blog import models

def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,
                                   status='published',
                                   publish__year=year,
                                   publish__month=month,
                                   publish__day=day)
    # List of active comments for this post
    comments = post.comments.filter(active=True)
    new_comment = None
    if request.method == 'POST':
        # A comment was posted
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
    else:
        comment_form = CommentForm()
    return render(request,
                  'blog/post/detail.html',
                  {'post': post,
                  'comments': comments, 
                  'new_comment': new_comment,
                  'comment_form': comment_form})


class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'
def post_list(request, tag_slug=None):
   object_list = Post.published.all()
   tag = None
   
   if tag_slug:
       tag = get_object_or_404(Tag, slug=tag_slug)
       object_list = object_list.filter(tags__in=[tag])
       
   paginator = Paginator(object_list, 5) # 3 posts in each page
   page = request.GET.get('page')
   try:
       posts = paginator.page(page)
   except PageNotAnInteger:
       # If page is not an integer deliver the first page
       posts = paginator.page(1)
   except EmptyPage:
       # If page is out of range deliver last page of results
       posts = paginator.page(paginator.num_pages)
   return render(request, 'blog/post/list.html', {'page': page,
                                                  'posts': posts,
                                                  'tag': tag})


def contact(request):
    
   if request.method == 'POST':
       #增加数据
       a_title=request.POST['a_title']
       a_slug=request.POST['a_slug']
       a_author=request.user
       a_body=request.POST['a_body']
       models.Post.objects.create(title=a_title,slug=a_slug,author=a_author,body=a_body,status='published')

       object_list = Post.published.all()
       tag = None
       tag_slug=None
       if tag_slug:
           tag = get_object_or_404(Tag, slug=tag_slug)
           object_list = object_list.filter(tags__in=[tag])
       
       paginator = Paginator(object_list, 5) # 3 posts in each page
       page = request.GET.get('page')
       try:
           posts = paginator.page(page)
       except PageNotAnInteger:
       # If page is not an integer deliver the first page
            posts = paginator.page(1)
       except EmptyPage:
       # If page is out of range deliver last page of results
            posts = paginator.page(paginator.num_pages)
       return render(request, 'blog/post/list.html', {'page': page,
                                                  'posts': posts,
                                                  'tag': tag})
       
   post_list = models.Post.objects.all()
   return render(request, 'blog/post/bbs_pub.html', {'post_list': post_list})    

travel/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from .models import Travel, travelComment
from .forms import CommentForm
from taggit.models import Tag
from travel import models

def travel_detail(request, year, month, day, post):
    travel = get_object_or_404(Travel, slug=post,
                                   status='published',
                                   publish__year=year,
                                   publish__month=month,
                                   publish__day=day)
    # List of active comments for this post
    comments = travel.comments.filter(active=True)
    new_comment = None
    if request.method == 'POST':
        # A comment was posted
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = travel
            # Save the comment to the database
            new_comment.save()
    else:
        comment_form = CommentForm()
    return render(request,
                  'blog/travel/detail.html',
                  {'travel': travel,
                  'comments': comments, 
                  'new_comment': new_comment,
                  'comment_form': comment_form})
    

class TravelListView(ListView):
    queryset = Travel.published.all()
    context_object_name = 'travels'
    paginate_by = 3
    template_name = 'blog/travel/list.html'
def travel_list(request, tag_slug=None):
   object_list = Travel.published.all()
   tag = None
   
   if tag_slug:
       tag = get_object_or_404(Tag, slug=tag_slug)
       object_list = object_list.filter(tags__in=[tag])
       
   paginator = Paginator(object_list, 5) # 3 posts in each page
   page = request.GET.get('page')
   try:
       travels = paginator.page(page)
   except PageNotAnInteger:
       # If page is not an integer deliver the first page
       travels = paginator.page(1)
   except EmptyPage:
       # If page is out of range deliver last page of results
       travels = paginator.page(paginator.num_pages)
   return render(request, 'blog/travel/list.html', {'page': page,
                                                  'travels': travels,
                                                  'tag': tag})
def contact(request):
    
   if request.method == 'POST':
       #增加数据
       a_title=request.POST['a_title']
       a_slug=request.POST['a_slug']
       a_author=request.user
       a_body=request.POST['a_body']
       models.Travel.objects.create(title=a_title,slug=a_slug,author=a_author,body=a_body,status='published')

       object_list = Travel.published.all()
       tag = None
       tag_slug = None
       if tag_slug:
              tag = get_object_or_404(Tag, slug=tag_slug)
              object_list = object_list.filter(tags__in=[tag])
       
       paginator = Paginator(object_list, 5) # 3 posts in each page
       page = request.GET.get('page')
       try:
              travels = paginator.page(page)
       except PageNotAnInteger:
              # If page is not an integer deliver the first page
              travels = paginator.page(1)
       except EmptyPage:
              # If page is out of range deliver last page of results
              travels = paginator.page(paginator.num_pages)
       return render(request, 'blog/travel/list.html', {'page': page,
                                                  'travels': travels,
                                                  'tag': tag})
       
       
       
   post_list = models.Travel.objects.all()
   return render(request, 'blog/travel/bbs_pub.html', {'post_list': post_list})   

templates/blog/travel/bbs_pub.html
<link href="/static/css/signin.css" rel="stylesheet">
{% extends 'index.html' %}
 
{% block page-content %}
 
<!-- Place inside the <head> of your HTML -->
<script type="text/javascript" src="/static/tinymce/js/tinymce/tinymce.min.js"></script>
<script type="text/javascript">

tinymce.init({
    selector: "textarea",
    theme: "modern",
    plugins: [
        "advlist autolink lists link image charmap print preview hr anchor pagebreak",
        "searchreplace wordcount visualblocks visualchars code fullscreen",
        "insertdatetime media nonbreaking save table contextmenu directionality",
        "emoticons template paste textcolor colorpicker textpattern"
    ],
    toolbar1: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image",
    toolbar2: "print preview media | forecolor backcolor emoticons",
    image_advtab: true,
    templates: [
        {title: 'Test template 1', content: 'Test 1'},
        {title: 'Test template 2', content: 'Test 2'}
    ]
});
 
</script>
 <h1 align="center">发布帖子</h1>
<!-- Place this in the body of the page content -->
<form method="post" action="/travel/bbs_pub">{% csrf_token %}
    <h3  align="center">当前板块：旅游信息</h3>
    <hr>
    <h3>标题</h3>
    <input type="text" id="inputA" name="a_title" class="form-control" placeholder="" required onkeyup="fillB()"/>
    <hr>
    <h3>Slug</h3>
    <input type="text" id="inputB" name="a_slug" class="form-control" placeholder="" required>
    <hr>
    <h3>内容</h3>
    <textarea name="a_body" cols="40" rows="10" class="form-control" placeholder="" required>
</textarea>
    <hr>
    <div class="form-signin">
        <button class="btn btn-lg btn-primary btn-block" type="submit">发表</button>
    </div>
{#    <input type='submit' value='Save' />#}
</form>
 
 
{% endblock %}

templates/blog/travel/detail.html
{% extends "blog/base.html" %}
{%   block page-content%}

{% block travel %}
   <h2>
      <a href="{{ travel.get_absolute_url }}">
        {{ travel.title }}
      </a>
    </h2>
  <p class="date">
    Published {{ travel.publish }} by {{ travel.author }}
  </p>
  {{ travel.body|linebreaks }}
{% with comments.count as total_comments %}
  <h2>
    {{ total_comments }} 个评论
  </h2>
{% endwith %}
{% for comment in comments %}
  <div class="comment">
    <p class="info">
      Comment {{ forloop.counter }} 楼 by {{ comment.name }}
      {{ comment.created }}
    </p>
    {{ comment.body|linebreaks }}
  </div>
  <br>
{% empty %}
  <p>这儿还没有人讨论呢。</p>
{% endfor %}
{% if new_comment %}
  <h2>您的评论已提交成功。</h2>
  
    <h2>继续讨论↓</h2>
  <form action="." method="post">
    {{ comment_form.as_p }}
    {% csrf_token %}
    <p><input type="submit" value="评论"></p>
  </form>
  
{% else %}
  <h2>说点什么吧↓</h2>
  <form action="." method="post">
    {{ comment_form.as_p }}
    {% csrf_token %}
    <p><input type="submit" value="评论"></p>
  </form>
{% endif %}

{% endblock %}
{% endblock %}

templates/blog/travel/list.html
{% extends "blog/base.html" %}
{% block page-content%}
{% block travel %}
  <h1 align="center">旅游信息版块</h1>
  <hr style="height:1px;border:none;border-top:1px dashed #0066CC;" /> 
   <ul class="nav nav-pills navbar-right" role="tablist">
         <li role="presentation" class="active">
              <a href="/travel/bbs_pub">发帖</a>
         </li>
   </ul>   
  {% if tag %}
    <h2>Posts tagged with "{{ tag.name }}"</h2>
  {% endif %}

  {% for travel in travels %}
    <h2>
      <a href="{{ travel.get_absolute_url }}">{{ travel.title }}</a>
    </h2>
    
<!-- 显示tags的内容   -->
    <p class="tags">
    标签:
    {% for tag in travel.tags.all %}
    <a href="{% url "travel:travel_list_by_tag" tag.slug %}">{{ tag.name }}</a>
    {% if not forloop.last %}, {% endif %}
    {% endfor %}
    </p>

    <p class="date">
      Published {{ travel.publish }} by {{ travel.author }}
    </p>
    {{ travel.body|truncatewords:30|linebreaks }}
  {% endfor %}
 
  {% include "pagination.html" with page=travels %}

{% endblock %}
{% endblock %}